# NumPy

### Intro

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
print('type: ', type(a))

type:  <class 'numpy.ndarray'>


In [4]:
print('shape: ', a.shape)
print('indexes: ', a[0])

shape:  (3,)
indexes:  1


In [5]:
a[0] = 5 
print(a[0])

5


In [8]:
arr = np.array(
   [
    [1, 2],
    [4, 5],
    [3, 6]
   ] 
)
print(arr)
print(type(arr))
print(arr.shape)

print(arr + 3.2)

[[1 2]
 [4 5]
 [3 6]]
<class 'numpy.ndarray'>
(3, 2)
[[4.2 5.2]
 [7.2 8.2]
 [6.2 9.2]]


In [11]:
ones_match = np.ones_like(arr)

print('ones_match: ')
print(ones_match)

ones_match: 
[[1 1]
 [1 1]
 [1 1]]


### reshaping before scalar dot prod.

In [34]:
ones_match = ones_match.reshape((2, 3))
prod = np.dot(arr, ones_match)
print(prod)

[[3 3 3]
 [9 9 9]
 [9 9 9]]


### dot product

In [19]:
a = [[1, 2],[4, 5]]
b = [[1, 1],[1, 1]]
np.dot(a, b)

array([[3, 3],
       [9, 9]])

In [21]:
a = [[1, 2],[4, 5]]
b = np.ones_like(a)
np.dot(a, b)

array([[3, 3],
       [9, 9]])

### slicing

In [31]:
a = np.arange(10)
print(a)
b = a[2:7]
c = a[2:7:2]
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [39]:
first_row = prod[:1]
print(prod)
print('first row: ', first_row)

[[3 3 3]
 [9 9 9]
 [9 9 9]]
first row:  [[3 3 3]]


In [46]:
s = np.sum(first_row)
print("sum: ", s)

sum:  9


### fliping

In [47]:
x = [[1, 2, 3],
    [4, 5, 6]]
frx = np.fliplr(x)
fx = np.flip(x)
print(x)
print(frx)
print(fx)

[[1, 2, 3], [4, 5, 6]]
[[3 2 1]
 [6 5 4]]
[[6 5 4]
 [3 2 1]]


### tiling

In [57]:
enyo = np.array(np.arange(10))
print(enyo)
t_enyo = np.tile(enyo, 3)
print(t_enyo)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [59]:
## reshaping tiles
st_enyo = np.tile(enyo, (3, 1))
print(st_enyo)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [62]:
! ls -l

total 8
-rw-r--r-- 1 pi pi 6953 Nov 14 12:56 Intro.ipynb


#### TODO: investigate "persising"