# NumPy

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
print('type: ', type(a))

type:  <class 'numpy.ndarray'>


In [4]:
print('shape: ', a.shape)
print('indexes: ', a[0])

shape:  (3,)
indexes:  1


In [5]:
a[0] = 5 
print(a[0])

5


In [8]:
arr = np.array(
   [
    [1, 2],
    [4, 5],
    [3, 6]
   ] 
)
print(arr)
print(type(arr))
print(arr.shape)

print(arr + 3.2)

[[1 2]
 [4 5]
 [3 6]]
<class 'numpy.ndarray'>
(3, 2)
[[4.2 5.2]
 [7.2 8.2]
 [6.2 9.2]]


In [11]:
ones_match = np.ones_like(arr)
print('ones_match: ')
print(ones_match)

ones_match: 
[[1 1]
 [1 1]
 [1 1]]
